package com.pristine.service.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2014-12-15T15:28:09.401+05:30
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://wsdl.service.pristine.com/", name = "ICatTypeMasterServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ICatTypeMasterServicePortType {

    @RequestWrapper(localName = "deleteCategoryType", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.DeleteCategoryType")
    @WebMethod
    @ResponseWrapper(localName = "deleteCategoryTypeResponse", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.DeleteCategoryTypeResponse")
    public void deleteCategoryType(
        @WebParam(name = "arg0", targetNamespace = "")
        com.pristine.service.wsdl.CategoryTypeMasterVO arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCategoryTypeById", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.GetCategoryTypeById")
    @WebMethod
    @ResponseWrapper(localName = "getCategoryTypeByIdResponse", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.GetCategoryTypeByIdResponse")
    public com.pristine.service.wsdl.CategoryTypeMasterVO getCategoryTypeById(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateCategoryType", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.UpdateCategoryType")
    @WebMethod
    @ResponseWrapper(localName = "updateCategoryTypeResponse", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.UpdateCategoryTypeResponse")
    public java.lang.Integer updateCategoryType(
        @WebParam(name = "arg0", targetNamespace = "")
        com.pristine.service.wsdl.CategoryTypeMasterVO arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createCategoryType", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.CreateCategoryType")
    @WebMethod
    @ResponseWrapper(localName = "createCategoryTypeResponse", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.CreateCategoryTypeResponse")
    public java.lang.Integer createCategoryType(
        @WebParam(name = "arg0", targetNamespace = "")
        com.pristine.service.wsdl.CategoryTypeMasterVO arg0
    );
}
