package com.pristine.service.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2014-12-15T15:28:09.591+05:30
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://wsdl.service.pristine.com/", name = "ICountryMasterServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ICountryMasterServicePortType {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getStatesByCountryId", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.GetStatesByCountryId")
    @WebMethod
    @ResponseWrapper(localName = "getStatesByCountryIdResponse", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.GetStatesByCountryIdResponse")
    public java.util.List<com.pristine.service.wsdl.StateMasterVO> getStatesByCountryId(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0
    );

    @RequestWrapper(localName = "updateCountryMaster", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.UpdateCountryMaster")
    @WebMethod
    @ResponseWrapper(localName = "updateCountryMasterResponse", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.UpdateCountryMasterResponse")
    public void updateCountryMaster(
        @WebParam(name = "arg0", targetNamespace = "")
        com.pristine.service.wsdl.CountryMasterVO arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createCountryMaster", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.CreateCountryMaster")
    @WebMethod
    @ResponseWrapper(localName = "createCountryMasterResponse", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.CreateCountryMasterResponse")
    public java.lang.Integer createCountryMaster(
        @WebParam(name = "arg0", targetNamespace = "")
        com.pristine.service.wsdl.CountryMasterVO arg0
    );

    @RequestWrapper(localName = "deleteCountryMaster", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.DeleteCountryMaster")
    @WebMethod
    @ResponseWrapper(localName = "deleteCountryMasterResponse", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.DeleteCountryMasterResponse")
    public void deleteCountryMaster(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCountryMaster", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.GetCountryMaster")
    @WebMethod
    @ResponseWrapper(localName = "getCountryMasterResponse", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.GetCountryMasterResponse")
    public com.pristine.service.wsdl.CountryMasterVO getCountryMaster(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0
    );
}
