package com.pristine.service.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2014-12-15T15:28:09.720+05:30
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://wsdl.service.pristine.com/", name = "ICustomerServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ICustomerServicePortType {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findCustomerById", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.FindCustomerById")
    @WebMethod
    @ResponseWrapper(localName = "findCustomerByIdResponse", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.FindCustomerByIdResponse")
    public com.pristine.service.wsdl.CustomerVO findCustomerById(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0
    );

    @RequestWrapper(localName = "deletePhone", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.DeletePhone")
    @WebMethod
    @ResponseWrapper(localName = "deletePhoneResponse", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.DeletePhoneResponse")
    public void deletePhone(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "persistCustomer", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.PersistCustomer")
    @WebMethod
    @ResponseWrapper(localName = "persistCustomerResponse", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.PersistCustomerResponse")
    public java.lang.Integer persistCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        com.pristine.service.wsdl.CustomerVO arg0
    );

    @RequestWrapper(localName = "deleteCustomer", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.DeleteCustomer")
    @WebMethod
    @ResponseWrapper(localName = "deleteCustomerResponse", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.DeleteCustomerResponse")
    public void deleteCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        com.pristine.service.wsdl.CustomerVO arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateCustomer", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.UpdateCustomer")
    @WebMethod
    @ResponseWrapper(localName = "updateCustomerResponse", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.UpdateCustomerResponse")
    public java.lang.Integer updateCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        com.pristine.service.wsdl.CustomerVO arg0
    );
}
