package com.pristine.service.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2014-12-15T15:28:10.099+05:30
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://wsdl.service.pristine.com/", name = "IDoctorMasterServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface IDoctorMasterServicePortType {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDoctorMaster", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.GetDoctorMaster")
    @WebMethod
    @ResponseWrapper(localName = "getDoctorMasterResponse", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.GetDoctorMasterResponse")
    public com.pristine.service.wsdl.DoctorMasterVO getDoctorMaster(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateDoctorMaster", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.UpdateDoctorMaster")
    @WebMethod
    @ResponseWrapper(localName = "updateDoctorMasterResponse", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.UpdateDoctorMasterResponse")
    public java.lang.Integer updateDoctorMaster(
        @WebParam(name = "arg0", targetNamespace = "")
        com.pristine.service.wsdl.DoctorMasterVO arg0
    );

    @RequestWrapper(localName = "deleteDoctorMaster", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.DeleteDoctorMaster")
    @WebMethod
    @ResponseWrapper(localName = "deleteDoctorMasterResponse", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.DeleteDoctorMasterResponse")
    public void deleteDoctorMaster(
        @WebParam(name = "arg0", targetNamespace = "")
        com.pristine.service.wsdl.DoctorMasterVO arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createDoctorMaster", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.CreateDoctorMaster")
    @WebMethod
    @ResponseWrapper(localName = "createDoctorMasterResponse", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.CreateDoctorMasterResponse")
    public java.lang.Integer createDoctorMaster(
        @WebParam(name = "arg0", targetNamespace = "")
        com.pristine.service.wsdl.DoctorMasterVO arg0
    );
}
