package com.pristine.service.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2014-12-15T15:28:09.994+05:30
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://wsdl.service.pristine.com/", name = "IEmployeeServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface IEmployeeServicePortType {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findEmployeeById", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.FindEmployeeById")
    @WebMethod
    @ResponseWrapper(localName = "findEmployeeByIdResponse", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.FindEmployeeByIdResponse")
    public com.pristine.service.wsdl.EmployeeVO findEmployeeById(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @RequestWrapper(localName = "deleteEmployee", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.DeleteEmployee")
    @WebMethod
    @ResponseWrapper(localName = "deleteEmployeeResponse", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.DeleteEmployeeResponse")
    public void deleteEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        com.pristine.service.wsdl.EmployeeVO arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "persistEmployee", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.PersistEmployee")
    @WebMethod
    @ResponseWrapper(localName = "persistEmployeeResponse", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.PersistEmployeeResponse")
    public java.lang.String persistEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        com.pristine.service.wsdl.EmployeeVO arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateEmployee", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.UpdateEmployee")
    @WebMethod
    @ResponseWrapper(localName = "updateEmployeeResponse", targetNamespace = "http://wsdl.service.pristine.com/", className = "com.pristine.service.wsdl.UpdateEmployeeResponse")
    public java.lang.String updateEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        com.pristine.service.wsdl.EmployeeVO arg0
    );
}
